package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetTasksParams creates a new GetTasksParams object
// with the default values initialized.
func NewGetTasksParams() GetTasksParams {
	var ()
	return GetTasksParams{}
}

// GetTasksParams contains all the bound params for the get tasks operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetTasks
type GetTasksParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*the task number to use as latest
	  Required: true
	  In: query
	*/
	Latest int32
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetTasksParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qLatest, qhkLatest, _ := qs.GetOK("latest")
	if err := o.bindLatest(qLatest, qhkLatest, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetTasksParams) bindLatest(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("latest", "query")
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}
	if err := validate.RequiredString("latest", "query", raw); err != nil {
		return err
	}

	value, err := swag.ConvertInt32(raw)
	if err != nil {
		return errors.InvalidType("latest", "query", "int32", raw)
	}
	o.Latest = value

	return nil
}
