package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	"baremetal-provision-server-0.0.173/models"
)

// NewPutBaremetalsParams creates a new PutBaremetalsParams object
// with the default values initialized.
func NewPutBaremetalsParams() PutBaremetalsParams {
	var ()
	return PutBaremetalsParams{}
}

// PutBaremetalsParams contains all the bound params for the put baremetals operation
// typically these are obtained from a http.Request
//
// swagger:parameters PutBaremetals
type PutBaremetalsParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*the spec and deployment for creating the baremetal server
	  Required: true
	  In: body
	*/
	BaremetalSpecs *models.BaremetalsParameters
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *PutBaremetalsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.BaremetalsParameters
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("baremetalSpecs", "body"))
			} else {
				res = append(res, errors.NewParseError("baremetalSpecs", "body", "", err))
			}

		} else {
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.BaremetalSpecs = &body
			}
		}

	} else {
		res = append(res, errors.Required("baremetalSpecs", "body"))
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
