package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PutBaremetalServerIDStateHandlerFunc turns a function with the right signature into a put baremetal server ID state handler
type PutBaremetalServerIDStateHandlerFunc func(PutBaremetalServerIDStateParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutBaremetalServerIDStateHandlerFunc) Handle(params PutBaremetalServerIDStateParams) middleware.Responder {
	return fn(params)
}

// PutBaremetalServerIDStateHandler interface for that can handle valid put baremetal server ID state params
type PutBaremetalServerIDStateHandler interface {
	Handle(PutBaremetalServerIDStateParams) middleware.Responder
}

// NewPutBaremetalServerIDState creates a new http.Handler for the put baremetal server ID state operation
func NewPutBaremetalServerIDState(ctx *middleware.Context, handler PutBaremetalServerIDStateHandler) *PutBaremetalServerIDState {
	return &PutBaremetalServerIDState{Context: ctx, Handler: handler}
}

/*PutBaremetalServerIDState swagger:route PUT /baremetal/{serverId}/{state} putBaremetalServerIdState

Update baremetal server state, e.g., curl -X PUT "http://10.12.20.17:8080/baremetal/981961/bm.state.new


*/
type PutBaremetalServerIDState struct {
	Context *middleware.Context
	Handler PutBaremetalServerIDStateHandler
}

func (o *PutBaremetalServerIDState) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewPutBaremetalServerIDStateParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
