package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PutBaremetalsHandlerFunc turns a function with the right signature into a put baremetals handler
type PutBaremetalsHandlerFunc func(PutBaremetalsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutBaremetalsHandlerFunc) Handle(params PutBaremetalsParams) middleware.Responder {
	return fn(params)
}

// PutBaremetalsHandler interface for that can handle valid put baremetals params
type PutBaremetalsHandler interface {
	Handle(PutBaremetalsParams) middleware.Responder
}

// NewPutBaremetals creates a new http.Handler for the put baremetals operation
func NewPutBaremetals(ctx *middleware.Context, handler PutBaremetalsHandler) *PutBaremetals {
	return &PutBaremetals{Context: ctx, Handler: handler}
}

/*PutBaremetals swagger:route PUT /baremetals putBaremetals

Create baremetal servers

*/
type PutBaremetals struct {
	Context *middleware.Context
	Handler PutBaremetalsHandler
}

func (o *PutBaremetals) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r)
	var Params = NewPutBaremetalsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
