---
platform: linux
image: docker:///zhanggongsw/bosh

inputs:
  - name: bosh-swagger
    path: gopath/src/github.com/zhanggbj/bosh-swagger

run:
  path: gopath/src/github.com/zhanggbj/bosh-swagger/ci/tasks/generate-server.sh