package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// ServerSpec server spec
// swagger:model ServerSpec
type ServerSpec struct {

	// cores
	Cores int32 `json:"cores,omitempty"`

	// whether this baremetal will be charged for by the hour or not
	Hourly bool `json:"hourly,omitempty"`

	// max port speed
	MaxPortSpeed int32 `json:"max_port_speed,omitempty"`

	// memory
	Memory int32 `json:"memory,omitempty"`

	// private vlan id
	PrivateVlanID int32 `json:"private_vlan_id,omitempty"`

	// public vlan id
	PublicVlanID int32 `json:"public_vlan_id,omitempty"`
}

// Validate validates this server spec
func (m *ServerSpec) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
