package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"baremetal-provision-server-0.0.170/models"
)

/*GetTasksTaskIDTxtLevelOK Successful response

swagger:response getTasksTaskIdTxtLevelOK
*/
type GetTasksTaskIDTxtLevelOK struct {

	// In: body
	Payload *models.TaskOutput `json:"body,omitempty"`
}

// NewGetTasksTaskIDTxtLevelOK creates GetTasksTaskIDTxtLevelOK with default headers values
func NewGetTasksTaskIDTxtLevelOK() *GetTasksTaskIDTxtLevelOK {
	return &GetTasksTaskIDTxtLevelOK{}
}

// WithPayload adds the payload to the get tasks task Id txt level o k response
func (o *GetTasksTaskIDTxtLevelOK) WithPayload(payload *models.TaskOutput) *GetTasksTaskIDTxtLevelOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tasks task Id txt level o k response
func (o *GetTasksTaskIDTxtLevelOK) SetPayload(payload *models.TaskOutput) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTasksTaskIDTxtLevelOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetTasksTaskIDTxtLevelDefault Unexpected error

swagger:response getTasksTaskIdTxtLevelDefault
*/
type GetTasksTaskIDTxtLevelDefault struct {
	_statusCode int

	// In: body
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetTasksTaskIDTxtLevelDefault creates GetTasksTaskIDTxtLevelDefault with default headers values
func NewGetTasksTaskIDTxtLevelDefault(code int) *GetTasksTaskIDTxtLevelDefault {
	if code <= 0 {
		code = 500
	}

	return &GetTasksTaskIDTxtLevelDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get tasks task ID txt level default response
func (o *GetTasksTaskIDTxtLevelDefault) WithStatusCode(code int) *GetTasksTaskIDTxtLevelDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get tasks task ID txt level default response
func (o *GetTasksTaskIDTxtLevelDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get tasks task ID txt level default response
func (o *GetTasksTaskIDTxtLevelDefault) WithPayload(payload *models.Error) *GetTasksTaskIDTxtLevelDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tasks task ID txt level default response
func (o *GetTasksTaskIDTxtLevelDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTasksTaskIDTxtLevelDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		if err := producer.Produce(rw, o.Payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
