resources:
- name: bosh-swagger
  type: git
  source:
    uri: https://github.com/zhanggbj/bosh-swagger.git
    branch: master

jobs:
- name: generate-server
  public: true
  plan:
  - get: bosh-swagger
    trigger: true

  - task: generate-server
    file: bosh-swagger/ci/tasks/generate-server.yml