package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetLoginUsernamePasswordParams creates a new GetLoginUsernamePasswordParams object
// with the default values initialized.
func NewGetLoginUsernamePasswordParams() GetLoginUsernamePasswordParams {
	var ()
	return GetLoginUsernamePasswordParams{}
}

// GetLoginUsernamePasswordParams contains all the bound params for the get login username password operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetLoginUsernamePassword
type GetLoginUsernamePasswordParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request

	/*the password
	  Required: true
	  In: path
	*/
	Password string
	/*the username
	  Required: true
	  In: path
	*/
	Username string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls
func (o *GetLoginUsernamePasswordParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error
	o.HTTPRequest = r

	rPassword, rhkPassword, _ := route.Params.GetOK("password")
	if err := o.bindPassword(rPassword, rhkPassword, route.Formats); err != nil {
		res = append(res, err)
	}

	rUsername, rhkUsername, _ := route.Params.GetOK("username")
	if err := o.bindUsername(rUsername, rhkUsername, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetLoginUsernamePasswordParams) bindPassword(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.Password = raw

	return nil
}

func (o *GetLoginUsernamePasswordParams) bindUsername(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	o.Username = raw

	return nil
}
