package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

// BaremetalsParameters baremetals parameters
// swagger:model BaremetalsParameters
type BaremetalsParameters struct {

	// baremetal specs
	BaremetalSpecs []*BaremetalSpecs `json:"baremetal_specs"`

	// the deployment name
	Deployment string `json:"deployment,omitempty"`
}

// Validate validates this baremetals parameters
func (m *BaremetalsParameters) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBaremetalSpecs(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BaremetalsParameters) validateBaremetalSpecs(formats strfmt.Registry) error {

	if swag.IsZero(m.BaremetalSpecs) { // not required
		return nil
	}

	for i := 0; i < len(m.BaremetalSpecs); i++ {

		if swag.IsZero(m.BaremetalSpecs[i]) { // not required
			continue
		}

		if m.BaremetalSpecs[i] != nil {

			if err := m.BaremetalSpecs[i].Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}
