package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// Login login
// swagger:model Login
type Login struct {

	// data
	Data string `json:"data,omitempty"`

	// status
	Status int32 `json:"status,omitempty"`
}

// Validate validates this login
func (m *Login) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
